<?php
/**
 * @var FormView $formView
 */
use Simplon\Form\View\FormView;

?>

<?php if ($formView->hasErrors()): ?>
    <div class="ui basic segment">
        <?= $formView->renderErrorMessage() ?>
    </div>
<?php endif ?>

<div class="ui basic segment">
    <h3>Default</h3>
    <?= $formView->getBlock('default')->render() ?>
</div>

<div class="ui basic segment">
    <h3>Dates</h3>
    <?= $formView->getBlock('dates')->render() ?>
</div>

<div class="ui basic segment">
    <h3>City</h3>
    <?= $formView->getBlock('cities')->render() ?>
</div>

<div class="ui basic segment">
    <h3>Image</h3>
    <?= $formView->getBlock('image')->render() ?>
    <div id="thumb"></div>
</div>

<div class="ui basic segment">
    <?= $formView->getSubmitElement()->renderElement() ?>
</div>