<?php
/**
 * @var FormView $formView
 */

use Simplon\Form\View\CloneFormViewBlock;
use Simplon\Form\View\FormView;
use Simplon\Form\View\FormViewBlock;

?>

<?php if ($formView->hasErrors()): ?>
    <div class="ui basic segment">
        <?= $formView->renderErrorMessage() ?>
    </div>
<?php endif ?>

<div class="ui basic segment">
    <h3>Bikes</h3>
    <?= $formView->getBlock('bikes')->render() ?>
</div>

<div class="ui basic segment">
    <h3>Address</h3>
    <?= CloneFormViewBlock::render($formView->getCloneBlocks('address'), function(FormViewBlock $block) {
        return $block->render();
    })?>
</div>

<div class="ui basic segment">
    <h3>Dates</h3>
    <?= CloneFormViewBlock::render($formView->getCloneBlocks('dates'), function(FormViewBlock $block) {
        return $block->render();
    })?>
</div>

<div class="ui basic segment">
    <h3>City</h3>
    <?= $formView->getBlock('cities')->render() ?>
</div>

<div class="ui basic segment">
    <h3>Tests</h3>
    <?= $formView->getBlock('tests')->render() ?>
    <div class="ui modal">
        <div class="header">Header</div>
        <div class="content">
            <p></p>
            <p></p>
            <p></p>
        </div>
    </div>
</div>

<div class="ui basic segment">
    <h3>Image</h3>
    <?= $formView->getBlock('image')->render() ?>
</div>

<div class="ui basic segment">
    <?= $formView->getSubmitElement()->renderElement() ?>
</div>